routes/web.php
<?php
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

Route::redirect('/', '/login');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');
Route::get('/news', 'NewsController@index')->name('news')->middleware('auth');
Route::get('/tips', 'TipsController@index')->name('tips')->middleware('auth');
Route::get('/intensityscale', 'IntensityScaleController@index')->name('intensityscale')->middleware('auth');
Route::get('/earthquakeinfo', 'EarthquakeInfoController@index')->name('earthquakeinfo')->middleware('auth');
Route::get('/tsunamiinfo', 'TsunamiInfoController@index')->name('tsunamiinfo')->middleware('auth');


// Route::group(['middleware' => 'auth'], function () {
// 		Route::get('icons', ['as' => 'pages.icons', 'uses' => 'PageController@icons']);
// 		Route::get('maps', ['as' => 'pages.maps', 'uses' => 'PageController@maps']);
// 		Route::get('notifications', ['as' => 'pages.notifications', 'uses' => 'PageController@notifications']);
// 		Route::get('rtl', ['as' => 'pages.rtl', 'uses' => 'PageController@rtl']);
// 		Route::get('tables', ['as' => 'pages.tables', 'uses' => 'PageController@tables']);
// 		Route::get('typography', ['as' => 'pages.typography', 'uses' => 'PageController@typography']);
// 		Route::get('upgrade', ['as' => 'pages.upgrade', 'uses' => 'PageController@upgrade']);
// });

Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);

	Route::get('/push-notificaiton', 'WebNotificationController@index')->name('push-notificaiton');
	Route::get('/news', 'NewsController@index')->name('news');
	Route::post('/store-token', 'WebNotificationController@storeToken')->name('store.token');
	Route::post('/send-web-notification', 'WebNotificationController@sendWebNotification')->name('send.web-notification');

	Route::resource('intent', 'IntentController', ['except' => ['show']]);
	// Route::post('/devicetoken', 'UserController@storeToken');
	Route::get('/send-alert/{id}', 'IntentController@sendAlert')->name('sendAlert');
});

// Route::post('/devicetoken', 'UserController@storeToken');

app/Intent.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Intent extends Model
{
    use SoftDeletes;

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'name',
        'level',
        'time',
        'date',
        'latitude',
        'depth',
        'magnitude',
        'epicenter',
        'created_at',
        'updated_at',
        'deleted_at',
    ];
}

app/Http/Controllers/IntentController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreIntentRequest;
use App\Intent;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use ExpoSDK\Expo;
use ExpoSDK\ExpoMessage;

class IntentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Intent $model)
    {
        abort_unless(Gate::allows('admin_access'), 403);
        return view('intent.index', ['intents' => $model->orderBy('id', 'desc')->paginate(15)]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        abort_unless(Gate::allows('admin_access'), 403);

        $intensities = ["2", "3", "4", "5", "6", "7", "8"];

        return view('intent.create', compact('intensities'));
    }

    public function sendAlert($id)
    {
        abort_unless(Gate::allows('admin_create'), 403);
        $users_tokens = User::all('device_key')
            ->where('device_key', '!=', null)
            ->where('device_key', '!=', 'false')
            ->toArray();

        //Send Push Notification

        $SERVER_API_KEY = 'AAAAC63GkIk:APA91bGYUaW9ewV044bLyciTr9-uvojJ2lCU8eYR3XmoPy9ZNEnpZOC-NZDTdWSgrSIkcYYkpLy7Xo5mkg1Bh-787BJej3b1ti-8xDb5TFjuZqBLuAYZI9iDdfkU9aoTRkPbzq_0TVDF';


        foreach ($users_tokens as $key => $value) {
            foreach ($value as $k => $val) {
                $data = [
                    "registration_ids" => [$val], // after registering on mobile automatic save device token
                    "notification" => [
                        "title" => "ShakeCDO Alert Message",
                        "body" => 'Intensity Level: ' . $id,
                        "sound" => 'alarm.mp3',
                        "color" => 'red',
                        "android_channel_id" => 'default',
                    ],
                    "data" => [
                        "url" => "https://earthq.page.link/home"
                    ],
                ];
                $dataString = json_encode($data);

                $headers = [
                    'Authorization: key=' . $SERVER_API_KEY,
                    'Content-Type: application/json',
                ];

                $ch = curl_init();

                curl_setopt($ch, CURLOPT_URL, 'https://fcm.googleapis.com/fcm/send');
                curl_setopt($ch, CURLOPT_POST, true);
                curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
                curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
                curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
                curl_setopt($ch, CURLOPT_POSTFIELDS, $dataString);

                $response = curl_exec($ch);
            }
        }


        return back()->withStatus(__('Intensity ' . $id . ' Alert! '));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        abort_unless(Gate::allows('admin_create'), 403);
        $users_tokens = User::all('device_key')
            ->where('device_key', '!=', null)
            ->where('device_key', '!=', 'false')
            ->toArray();

        $SERVER_API_KEY = 'AAAAC63GkIk:APA91bGYUaW9ewV044bLyciTr9-uvojJ2lCU8eYR3XmoPy9ZNEnpZOC-NZDTdWSgrSIkcYYkpLy7Xo5mkg1Bh-787BJej3b1ti-8xDb5TFjuZqBLuAYZI9iDdfkU9aoTRkPbzq_0TVDF';

        $int = Intent::create($request->all());
        $int->save();

        foreach ($users_tokens as $key => $value) {
            foreach ($value as $k => $val) {
                $data = [
                    "registration_ids" => [$val], // after registering on mobile automatic save device token
                    "notification" => [
                        "title" => "Area: " . $request->name,
                        "body" => 'Intensity Level: ' . $request->level . ' Time: ' . $request->time . ' Date: ' . $request->date . ' Latitude: ' . $request->latitude . ' Depth: ' . $request->depth . ' Magnitude: ' . $request->magnitude . ' Epicenter: ' . $request->epicenter,
                        "sound" => 'toot.mp3',
                        "color" => 'red',
                        "android_channel_id" => 'default',
                    ],
                ];
                $dataString = json_encode($data);

                $headers = [
                    'Authorization: key=' . $SERVER_API_KEY,
                    'Content-Type: application/json',
                ];

                $ch = curl_init();

                curl_setopt($ch, CURLOPT_URL, 'https://fcm.googleapis.com/fcm/send');
                curl_setopt($ch, CURLOPT_POST, true);
                curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
                curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
                curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
                curl_setopt($ch, CURLOPT_POSTFIELDS, $dataString);

                $response = curl_exec($ch);
            }
        }

        return redirect()->route('intent.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Intent $intent)
    {
        abort_unless(Gate::allows('admin_access'), 403);
        $intensities = ["2", "3", "4", "5", "6", "7", "8"];

        return view('intent.edit', compact('intent', 'intensities'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Intent $intent)
    {
        abort_unless(Gate::allows('admin_access'), 403);

        $intent->update($request->all());

        return redirect()->route('intent.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Intent::where('id', $id)->delete();

        return back();
    }
}

resources/views/intent/create.blade.php
@extends('layouts.app', ['page' => __('Intensity Alert'), 'pageSlug' => 'intent'])

@section('content')
<div class="container-fluid mt--7">
    <div class="row">
        <div class="col-xl-12 order-xl-1">
            <div class="card">
                <div class="card-header">
                    <div class="row align-items-center">
                        <div class="col-8">
                            <h3 class="mb-0">{{ __('Intensity Information') }}</h3>
                        </div>
                        <div class="col-4 text-right">
                            <a href="{{ route('intent.index') }}" class="btn btn-sm btn-primary">{{ __('Back to list') }}</a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <form method="post" action="{{ route('intent.store') }}" autocomplete="off">
                        @csrf

                        <h6 class="heading-small text-muted mb-4">{{ __('Intensity Information') }}</h6>
                        <div class="pl-lg-4">
                            <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                                <label class="form-control-label" for="input-name">{{ __('Name of Area') }}</label>
                                <input type="text" name="name" id="input-name" class="form-control form-control-alternative{{ $errors->has('name') ? ' is-invalid' : '' }}" placeholder="{{ __('Name') }}" value="{{ old('name') }}" required autofocus>
                                @include('alerts.feedback', ['field' => 'name'])
                            </div>
                            <div class="form-group {{ $errors->has('level') ? 'has-error' : '' }}">
                                <label for="level">Alert Level*</label>
                                <select name="level" id="level" class="form-control select">
                                    @foreach($intensities as $id => $intensities)
                                    <option value="{{ $intensities }}" {{ (in_array($id, old('level', [])) || isset($user) && $user->level->contains($id)) ? 'selected' : '' }}>
                                        {{ $intensities }}
                                    </option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group{{ $errors->has('time') ? ' has-danger' : '' }}">
                                <label class="form-control-label" for="input-time">{{ __('Time') }}</label>
                                <input type="time" name="time" id="input-time" class="form-control form-control-alternative{{ $errors->has('time') ? ' is-invalid' : '' }}" placeholder="{{ __('Time') }}" value="{{ old('time') }}" required autofocus>
                                @include('alerts.feedback', ['field' => 'time'])
                            </div>
                            <div class="form-group{{ $errors->has('date') ? ' has-danger' : '' }}">
                                <label class="form-control-label" for="input-date">{{ __('Date') }}</label>
                                <input type="date" name="date" id="input-date" class="form-control form-control-alternative{{ $errors->has('date') ? ' is-invalid' : '' }}" placeholder="{{ __('Date') }}" value="{{ old('date') }}" required autofocus>
                                @include('alerts.feedback', ['field' => 'date'])
                            </div>
                            <div class="form-group{{ $errors->has('latitude') ? ' has-danger' : '' }}">
                                <label class="form-control-label" for="input-latitude">{{ __('Latitude') }}</label>
                                <input type="text" name="latitude" id="input-latitude" class="form-control form-control-alternative{{ $errors->has('latitude') ? ' is-invalid' : '' }}" placeholder="{{ __('Latitude') }}" value="{{ old('latitude') }}" required autofocus>
                                @include('alerts.feedback', ['field' => 'latitude'])
                            </div>
                            <div class="form-group{{ $errors->has('depth') ? ' has-danger' : '' }}">
                                <label class="form-control-label" for="input-depth">{{ __('Depth') }}</label>
                                <input type="text" name="depth" id="input-depth" class="form-control form-control-alternative{{ $errors->has('depth') ? ' is-invalid' : '' }}" placeholder="{{ __('Depth') }}" value="{{ old('depth') }}" required autofocus>
                                @include('alerts.feedback', ['field' => 'depth'])
                            </div>
                            <div class="form-group{{ $errors->has('magnitude') ? ' has-danger' : '' }}">
                                <label class="form-control-label" for="input-magnitude">{{ __('Magnitude') }}</label>
                                <input type="text" name="magnitude" id="input-magnitude" class="form-control form-control-alternative{{ $errors->has('magnitude') ? ' is-invalid' : '' }}" placeholder="{{ __('Magnitude') }}" value="{{ old('magnitude') }}" required autofocus>
                                @include('alerts.feedback', ['field' => 'magnitude'])
                            </div>
                            <div class="form-group{{ $errors->has('epicenter') ? ' has-danger' : '' }}">
                                <label class="form-control-label" for="input-epicenter">{{ __('Epicenter / Location') }}</label>
                                <input type="text" name="epicenter" id="input-epicenter" class="form-control form-control-alternative{{ $errors->has('epicenter') ? ' is-invalid' : '' }}" placeholder="{{ __('Epicenter') }}" value="{{ old('epicenter') }}" required autofocus>
                                @include('alerts.feedback', ['field' => 'epicenter'])
                            </div>
                        </div>
                        <div class="text-center">
                            <button type="submit" class="btn btn-success mt-4">{{ __('Save') }}</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/intent/edit.blade.php
@extends('layouts.app', ['page' => __('Intensity Alert'), 'pageSlug' => 'intent'])

@section('content')
<div class="container-fluid mt--7">
    <div class="row">
        <div class="col-xl-12 order-xl-1">
            <div class="card">
                <div class="card-header">
                    <div class="row align-items-center">
                        <div class="col-8">
                            <h3 class="mb-0">{{ __('Intensity Information') }}</h3>
                        </div>
                        <div class="col-4 text-right">
                            <a href="{{ route('intent.index') }}" class="btn btn-sm btn-primary">{{ __('Back to list') }}</a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <form method="post" action="{{ route('intent.update', $intent) }}" autocomplete="off">
                        @csrf
                        @method('put')

                        <h6 class="heading-small text-muted mb-4">{{ __('Additional Data') }}</h6>
                        <div class="pl-lg-4">
                            <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                                <label class="form-control-label" for="input-name">{{ __('Name of Area') }}</label>
                                <input type="text" name="name" id="input-name" class="form-control form-control-alternative{{ $errors->has('name') ? ' is-invalid' : '' }}" placeholder="{{ __('Name') }}" value="{{ old('name', $intent->name) }}" required autofocus>
                                @include('alerts.feedback', ['field' => 'name'])
                            </div>
                            <div class="form-group {{ $errors->has('level') ? 'has-error' : '' }}">
                                <label for="level">Level*</label>
                                <select name="level" id="level" class="form-control select">
                                    @foreach ($intensities as $id => $intensities)
                                    <option value="{{ $intensities }}" {{ $intent->level == $intensities ? 'selected' : '' }}>
                                        {{ $intensities }}
                                    </option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group{{ $errors->has('time') ? ' has-danger' : '' }}">
                                <label class="form-control-label" for="input-time">{{ __('Time') }}</label>
                                <input type="time" name="time" id="input-time" class="form-control form-control-alternative{{ $errors->has('time') ? ' is-invalid' : '' }}" placeholder="{{ __('Time') }}" value="{{ old('time', $intent->time) }}" required autofocus>
                                @include('alerts.feedback', ['field' => 'time'])
                            </div>
                            <div class="form-group{{ $errors->has('date') ? ' has-danger' : '' }}">
                                <label class="form-control-label" for="input-date">{{ __('Date') }}</label>
                                <input type="date" name="date" id="input-date" class="form-control form-control-alternative{{ $errors->has('date') ? ' is-invalid' : '' }}" placeholder="{{ __('Date') }}" value="{{ old('date', $intent->date) }}" required autofocus>
                                @include('alerts.feedback', ['field' => 'date'])
                            </div>
                            <div class="form-group{{ $errors->has('latitude') ? ' has-danger' : '' }}">
                                <label class="form-control-label" for="input-latitude">{{ __('Latitude') }}</label>
                                <input type="text" name="latitude" id="input-latitude" class="form-control form-control-alternative{{ $errors->has('latitude') ? ' is-invalid' : '' }}" placeholder="{{ __('Latitude') }}" value="{{ old('latitude', $intent->latitude) }}" required autofocus>
                                @include('alerts.feedback', ['field' => 'latitude'])
                            </div>
                            <div class="form-group{{ $errors->has('depth') ? ' has-danger' : '' }}">
                                <label class="form-control-label" for="input-depth">{{ __('Depth') }}</label>
                                <input type="text" name="depth" id="input-depth" class="form-control form-control-alternative{{ $errors->has('depth') ? ' is-invalid' : '' }}" placeholder="{{ __('Depth') }}" value="{{ old('depth', $intent->depth) }}" required autofocus>
                                @include('alerts.feedback', ['field' => 'depth'])
                            </div>
                            <div class="form-group{{ $errors->has('magnitude') ? ' has-danger' : '' }}">
                                <label class="form-control-label" for="input-magnitude">{{ __('Magnitude') }}</label>
                                <input type="text" name="magnitude" id="input-magnitude" class="form-control form-control-alternative{{ $errors->has('magnitude') ? ' is-invalid' : '' }}" placeholder="{{ __('Magnitude') }}" value="{{ old('magnitude', $intent->magnitude) }}" required autofocus>
                                @include('alerts.feedback', ['field' => 'magnitude'])
                            </div>
                            <div class="form-group{{ $errors->has('epicenter') ? ' has-danger' : '' }}">
                                <label class="form-control-label" for="input-epicenter">{{ __('Epicenter / Location') }}</label>
                                <input type="text" name="epicenter" id="input-epicenter" class="form-control form-control-alternative{{ $errors->has('epicenter') ? ' is-invalid' : '' }}" placeholder="{{ __('Epicenter') }}" value="{{ old('epicenter', $intent->epicenter) }}" required autofocus>
                                @include('alerts.feedback', ['field' => 'epicenter'])
                            </div>

                            <div class="text-center">
                                <button type="submit" class="btn btn-success mt-4">{{ __('Save') }}</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/intent/index.blade.php
@extends('layouts.app', ['page' => __('Intensity Alert'), 'pageSlug' => 'intent'])

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card ">
            <div class="card-header">
                <div class="row">
                    <div class="col-8">
                        <h4 class="card-title">{{ __('Intensity Alert') }}</h4>
                    </div>
                    <div class="col-4 text-right">
                        <a href="{{ route('intent.create') }}" class="btn btn-sm btn-primary">{{ __('Add Alert') }}</a>
                    </div>
                </div>
            </div>
            <div class="card-body">
                @include('alerts.success')

                <div class="">
                    <table class="table tablesorter " id="">
                        <thead class=" text-primary">
                            <th scope="col">{{ __('Name') }}</th>
                            <th scope="col">{{ __('Level') }}</th>
                            <th scope="col">{{ __('Creation Date') }}</th>
                            <th scope="col"></th>
                        </thead>
                        <tbody>
                            @foreach ($intents as $intent)
                            <tr>
                                <td>{{ $intent->name }}</td>
                                <td>{{ $intent->level }}</td>
                                <td>{{ $intent->created_at->format('d/m/Y H:i') }}</td>
                                <td class="text-right">
                                    <div class="dropdown">
                                        <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <i class="fas fa-ellipsis-v"></i>
                                        </a>
                                        <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                            <form action="{{ route('intent.destroy', $intent->id) }}" method="post">
                                                @csrf
                                                @method('delete')

                                                <a class="dropdown-item" href="{{ route('intent.edit', $intent) }}">{{ __('Edit') }}</a>
                                                <button type="button" class="dropdown-item" onclick="confirm('{{ __("Are you sure you want to delete this user?") }}') ? this.parentElement.submit() : ''">
                                                    {{ __('Delete') }}
                                                </button>
                                            </form>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection